# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160924_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(null=True, to='categories.Category'),
        ),
    ]
