# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(choices=[('POL', 'Política'), ('ECO', 'Economía'), ('SOC', 'Sociedad'), ('DEP', 'Deportes'), ('CUL', 'Cultura'), ('CIE', 'Ciencia')], max_length=3)),
            ],
        ),
    ]
