# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tipo_categoria',
            field=models.CharField(max_length=20),
        ),
    ]
